// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "NativeGameplayTags.h"

namespace ActionGameProjectGameplayTags
{
	/* Input Tags */
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look);
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_EquipAxe);
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_UnequipAxe);
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_LightAttack_Axe);
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_HeavyAttack_Axe);
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Sprint_Start);
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Sprint_Stop);


	/* Player Tags */
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Equip_Axe);
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Unequip_Axe);
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Attack_Light_Axe);
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Attack_Heavy_Axe);
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Sprint_Start);
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Sprint_Stop);

	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Weapon_Axe);

	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Equip_Axe);
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Unequip_Axe);

	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_JumpToFinisher);


	/* Enemy Tags */
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Weapon);
	
}

